language: cpp
sudo: false
env:
  global: GRPC_VERSION=v1.0.1
matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - golang
        - gcc-4.8
        - g++-4.8
    script:
    - env CC=gcc-4.8 CXX=g++-4.8 ./build_grpc.sh $GRPC_VERSION
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - golang
        - gcc-5
        - g++-5
    script:
    - env CC=gcc-5 CXX=g++-5 ./build_grpc.sh $GRPC_VERSION
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - golang
        - gcc-6
        - g++-6
    script:
    - env CC=gcc-6 CXX=g++-6 ./build_grpc.sh $GRPC_VERSION
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.5
        packages:
        - golang
        - clang-3.5
    script:
    - env CC=clang-3.5 CXX=clang++-3.5 ./build_grpc.sh $GRPC_VERSION
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        packages:
        - golang
        - clang-3.7
    script:
    - env CC=clang-3.7 CXX=clang++-3.7 ./build_grpc.sh $GRPC_VERSION
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.8
        packages:
        - golang
        - clang-3.8
    script:
    - env CC=clang-3.8 CXX=clang++-3.8 ./build_grpc.sh $GRPC_VERSION
before_script:
- echo "TRAVIS_TAG=$TRAVIS_TAG"
- echo "GRPC_VERSION=$GRPC_VERSION"
- uname -a
- ls
after_script:
- ls
notifications:
  email: false
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IMKMVmgnA5iRPQ2R1v24A2WO1xIcKjHGexfFFT24eSCVyQ0AgiFUI57vx1zprrN7WPBafU9g4RLzkRHU4Zihg3PfAR5QrlMfUhztcNlYOlcSM0mk8x2j6Lp27djXV3kJov6JW4S6yVS65hPI/WbRmdsq3D2vBxy7q30LA+wwYzd/zmeAIp3jjLDX8cb+Xle8fYL++bmDfRJu37sDb12q7f7bDsSxAydB/7cseM1ZZ6niwA6PrgSjcNqOnYhrCm5OG3+zvzZMrkdd++XwYMFsuYcpqHyMvSAtnLRB8xAaK9kEewHaRPbHbk+E5d02Tvq2Vls7pTHYJPMEF7sm8zA/qOPuIic8ocrNhcCoIsN/huY533DQ20p8DPMq0PobvUBk8MpBPZaFOkc2myhCoClmn0Yr8b0/E9r8ikvykcRXDKB9mrlarzNu6n0H/aOdJMHXLM7w+O9IQDzNfLJR9kGQBKZ7y6dGnQ3sRA8aIUjxs4EG1yIViocGyTBlzEuFqKC8/1ewHi9hIbibefvP43oNS6WbjhimYnaSfsfPZJexPKAJQm/zT9HkxlA4V1ZpXzNKfLZHrDpagtT7+7CnR23aRqaZ700g4TnJnOQfuFKDgu5dS+958j1PYMvfCUwGxcI3Yxzv4NO1aW+oF5OtVU9U/afNXmtwp1maC+LPtDp9noI=
  file: grpc-*.tar.gz
  file_glob: true
  on:
    tags: true
    repo: aurelienrb/build-grpc
